# Linux linker config, uses mold
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

# Windows linker config, uses LLD
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
